/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_simonis_NativeCall */

#ifndef _Included_io_simonis_NativeCall
#define _Included_io_simonis_NativeCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_simonis_NativeCall
 * Method:    simple
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_simonis_NativeCall_simple
  (JNIEnv *, jclass);

/*
 * Class:     io_simonis_NativeCall
 * Method:    hello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_simonis_NativeCall_hello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
