/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeCall */

#ifndef _Included_NativeCall
#define _Included_NativeCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeCall
 * Method:    nMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeCall_nMethod
  (JNIEnv *, jobject);

/*
 * Class:     NativeCall
 * Method:    nativeMethod
 * Signature: (ILjava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_NativeCall_nativeMethod__ILjava_lang_String_2_3B
  (JNIEnv *, jobject, jint, jstring, jbyteArray);

/*
 * Class:     NativeCall
 * Method:    nativeMethod
 * Signature: (DLjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_NativeCall_nativeMethod__DLjava_lang_Object_2
  (JNIEnv *, jclass, jdouble, jobject);

#ifdef __cplusplus
}
#endif
#endif
